### ***Python NumPy***

***NumPy Array***

In [1]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
print(array1)
print(array1.shape)
print(array1.size)
print(array1.ndim)
print(array1.dtype)

[1 2 3 4 5]
(5,)
5
1
int64


***Type Casting***

In [6]:
array1 = np.array([[10,20,30],[40,50,60],[70,"100",90]],dtype="int")
print(array1)
print(array1.dtype)

[[ 10  20  30]
 [ 40  50  60]
 [ 70 100  90]]
int64


In [7]:
array2 = np.array([[10,20,30],[40,50,60],[70,"100",90]],dtype="float")
print(array2)
print(array2.dtype)

[[ 10.  20.  30.]
 [ 40.  50.  60.]
 [ 70. 100.  90.]]
float64


***Array Filling***

In [ ]:
#full 
a = np.full((5,5),["Monkey", "Tiger", "Lion","Elephant", "Dog"])
print(a)

[['Monkey' 'Tiger' 'Lion' 'Elephant' 'Dog']
 ['Monkey' 'Tiger' 'Lion' 'Elephant' 'Dog']
 ['Monkey' 'Tiger' 'Lion' 'Elephant' 'Dog']
 ['Monkey' 'Tiger' 'Lion' 'Elephant' 'Dog']
 ['Monkey' 'Tiger' 'Lion' 'Elephant' 'Dog']]


In [9]:
#Zeros
b = np.zeros((5,5),dtype='int')
print(b)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [11]:
#Ones
c = np.ones((5,5), dtype='int')
print(c)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


***Arange***

In [ ]:
#Arange
print(np.arange(100,0,-10))

[100  90  80  70  60  50  40  30  20  10]


In [14]:
#Linespace
d = np.linspace(0,100,10)
print(d)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


***nan , inf***

In [15]:
#nan
print(np.sqrt(10))
print(np.sqrt(-10))
print("Hello Python")

3.1622776601683795
nan
Hello Python


C:\Users\Moham\AppData\Local\Temp\ipykernel_11980\1314031493.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-10))


In [20]:
#inf

print(np.array([10])/2)
print(np.array([10])/0)
print("Hello Master")

[5.]
[inf]
Hello Master


C:\Users\Moham\AppData\Local\Temp\ipykernel_11980\790026617.py:4: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10])/0)


***NumPy Array***

In [21]:
l1 = np.array([1,3,4,5,6])
l2 = np.array([7,8,9,10,0])
print(l1+l2)
print()
print(l1-l2)
print()
print(l1*l2)

[ 8 11 13 15  6]

[-6 -5 -5 -5  6]

[ 7 24 36 50  0]


In [22]:
#append
l1=np.array([1,2,3,4,5])
l1=np.append(l1,[6,7,8])
print(l1)

[1 2 3 4 5 6 7 8]


In [25]:
#insert
l1 = np.array([1,2,3,4,5])
l1 =np.insert([l1],2,[6,7,8])
print(l1)

[1 2 6 7 8 3 4 5]


***Delete Array***

In [37]:
#Deleting form in 2D Array

l1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(l1)
print()
print(np.delete(l1,[10,11,12]))
print()
print(np.delete(l1,[2,3], 1)) #column axis=1(2D array)
print()
print(np.delete(l1,1,0)) #row axix-0(2D array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[ 1  2  3  4  5  6  7  8  9 10 14 15]

[[ 1  2  5]
 [ 6  7 10]
 [11 12 15]]

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [39]:
#Deleting form in 3D Array

l2 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(l2)
print()
print(np.delete(l2,[7,8,9]))
print("Deleted the depth")
print(np.delete(l2,1,0)) #depth axis=0(3D array)
print("Deleted the row")
print(np.delete(l2,1,1)) #row axix=1(3D array)
print("Deleted the column")
print(np.delete(l2,1, 2)) #column axis=2(2D array)



[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]

[ 1  2  3  4  5  6  7 11 12 13 14 15 16 17 18 19 20]
Deleted the depth
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
Deleted the row
[[[ 1  2  3  4  5]]

 [[11 12 13 14 15]]]
Deleted the column
[[[ 1  3  4  5]
  [ 6  8  9 10]]

 [[11 13 14 15]
  [16 18 19 20]]]


***Array Filling random***

In [ ]:
np.random.seed(3)
a = np.random.rand(5,5)
print(a)

[[0.5507979  0.70814782 0.29090474 0.51082761 0.89294695]
 [0.89629309 0.12558531 0.20724288 0.0514672  0.44080984]
 [0.02987621 0.45683322 0.64914405 0.27848728 0.6762549 ]
 [0.59086282 0.02398188 0.55885409 0.25925245 0.4151012 ]
 [0.28352508 0.69313792 0.44045372 0.15686774 0.54464902]]


In [75]:
#Using int 
np.random.seed(3)
a = np.random.randint(1,10,(5,5))
print(a)

[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]
 [7 3 3 2 4]
 [6 9 2 9 8]]


In [77]:
# using unique to identify what are the random number in the array listed
print(np.unique(a))

[1 2 3 4 5 6 7 8 9]


***Idinticall matrices***  

To check if two matrices are completely identical in shape and elements using NumPy

In [78]:
print(a)

[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]
 [7 3 3 2 4]
 [6 9 2 9 8]]


In [82]:
b =np.full((5,5),5)
print(b)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [83]:
print(a+b)
print()
print(a*b)

[[14  9 14 14  6]
 [11  9 11 13 12]
 [ 6 10 13 14  7]
 [12  8  8  7  9]
 [11 14  7 14 13]]

[[45 20 45 45  5]
 [30 20 30 40 35]
 [ 5 25 40 45 10]
 [35 15 15 10 20]
 [30 45 10 45 40]]


***Non Idinticall matrices***   

Column size must be equal  
row size of one array must be equal to one

In [ ]:
import numpy as np

a = np.random.randint(1, 51, size=(5, 5)) 
b = np.random.randint(50, 101, size=(5, 1))
print(a)
print(b)


[[17 17 33 17 19]
 [12 33 32 14 38]
 [31 49 34 50  3]
 [29 37 27 41 45]
 [49 11 49 37 28]]
[[99]
 [71]
 [99]
 [90]
 [89]]


In [86]:
print(a+b)
print()
print(a*b)

[[116 116 132 116 118]
 [ 83 104 103  85 109]
 [130 148 133 149 102]
 [119 127 117 131 135]
 [138 100 138 126 117]]

[[1683 1683 3267 1683 1881]
 [ 852 2343 2272  994 2698]
 [3069 4851 3366 4950  297]
 [2610 3330 2430 3690 4050]
 [4361  979 4361 3293 2492]]


In [87]:
#slicing
print(a[2:, 2:]) 
print()
print(a[:2,:2])
print()

[[34 50  3]
 [27 41 45]
 [49 37 28]]

[[17 17]
 [12 33]]



***Time to run***

In [88]:
a = np.random.rand(500)
print(a)

[3.25807158e-01 4.45145049e-01 6.15289308e-02 2.42675422e-01
 9.71602606e-01 2.30584204e-01 6.91477511e-01 6.50476858e-01
 7.23939139e-01 4.75088611e-01 5.96663775e-01 6.69694239e-02
 7.25621378e-02 1.98976026e-01 1.51860997e-01 1.00104345e-01
 1.29293865e-01 5.53277732e-01 1.87814825e-01 9.52101243e-01
 6.81611779e-01 5.41019673e-01 7.07180601e-01 2.63886671e-01
 9.26725684e-01 8.39193058e-01 7.26319498e-01 4.80239956e-01
 8.42103186e-01 7.44752323e-01 6.60325906e-01 9.13975267e-01
 6.33665564e-01 3.65940585e-01 5.52844573e-01 1.96380577e-01
 1.92072296e-01 7.25669624e-01 7.84936703e-01 9.72098364e-01
 8.50971417e-01 5.43594327e-01 8.97908695e-02 4.88873245e-01
 9.27936348e-01 7.87618200e-01 4.85094226e-01 4.55279361e-01
 2.17985768e-01 1.77213381e-01 7.36236692e-02 8.92393188e-01
 6.40176617e-01 1.43332317e-01 4.14126920e-01 4.91089244e-02
 2.09373350e-01 7.30708124e-01 6.51122770e-01 4.78978297e-01
 2.74780505e-01 6.52223125e-01 9.56449511e-01 4.35520556e-01
 7.01325051e-02 5.773148

In [89]:
#python
%timeit sum(a) #python

30.3 μs ± 2.8 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [91]:
#numpy
%timeit np.sum(a) #numpy

2.74 μs ± 23.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


 ***dot product***

In [16]:
print(np.dot(a, b))

[[14267 12258 11368]
 [13648 12369 10842]
 [ 7748  6713  6619]
 [ 7984  6994  6204]
 [ 8546  7860  7221]]


***Reshape***

In [27]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(2,2,3)
print(arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
